stages:
  data_ingestion:
    cmd: python src/dataset.py
    deps:
    - src/dataset.py
    outs:
    - data/raw/
  
  data_preprocessing:
    cmd: python src/features.py
    deps:
    - data/raw/
    - src/features.py
    outs:
    - data/processed/
  
  modeling:
    cmd: python src/modeling/train.py
    deps:
    - data/processed/
    - src/modeling/train.py
    outs:
    - models/model.pkl
    
  model_evaluation:
    cmd: python src/modeling/predict.py
    deps:
    - models/model.pkl
    - src/modeling/predict.py
    metrics:
    - reports/metrics/metrics.json
    outs:
    - reports/run_info.json
  
  model_registration:
    cmd: python src/modeling/register.py
    deps:
    - reports/run_info.json
    - src/modeling/register.py
    
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
