name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  install_uv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup UV Python
        id: setup_uv
        uses: astral-sh/setup-uv@v5
        with:
          version: '0.6.2'
          python-version: '3.9.21'
          enable-cache: true
          cache-suffix: "optional-suffix"
          cache-dependency-glob: |
            **/requirements*.txt
      - run: uv python install 3.9.21
  
  install_dependencies:      
    needs: install_uv
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: uv pip install -r requirements.txt

  run_dvc_pipeline:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run DVC Pipeline
        run: dvc repro
