name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  ci_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup UV Python
        id: setup_uv
        uses: astral-sh/setup-uv@v5
        with:
          version: '0.6.2'
          python-version: '3.9.21'
          enable-cache: true
          cache-suffix: "optional-suffix"
          cache-dependency-glob: |
            **/requirements*.txt
      - run: uv python install 3.9.21

      - name: Install dependencies
        run: uv pip install -r requirements.txt

      - name: Run DVC Pipeline  
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }} 
        run: |
          echo $DAGSHUB_TOKEN
          dvc repro 
